### ISSUE TITLE
Buggy still

### ISSUE THREAD

**Issue by Senorsen** [QSCTech/ChinaDNS-C#1]
tons of bugs or errors in lookup, such as zuinfo.zju.edu.cn or other local sites.

So I switched dns of 73 back to dnsmasq, instead of this special version of ChinaDNS-C.

**Comment by zenozeng** [comment]
森森快学习。

**Comment by Senorsen** [comment]
Oh my zenozeng...

**Comment by Qusic** [comment]
hhhhhh
